version: '3.3'

services:
  ngp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ngp_data:/usr/src/npg/data/
    restart: always

volumes:
  ngp_data:
